---
name: Lint Code Base
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
          version: latest
